
"""report.py — 投资报告渲染引擎"""
import os, io, base64
from datetime import datetime, timedelta
from pathlib import Path
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import matplotlib.ticker as mticker
import pandas as pd
import numpy as np

from env import IE_ROOT

def _fig_to_base64(fig):
    buf = io.BytesIO()
    fig.savefig(buf, format="png", dpi=100, bbox_inches="tight")
    buf.seek(0)
    img = base64.b64encode(buf.read()).decode("utf-8")
    plt.close(fig)
    return img

def plot_ic_bar(ic_data: pd.Series) -> str:
    if ic_data.empty:
        return ""
    fig, ax = plt.subplots(figsize=(10, 4))
    colors = ["#e74c3c" if v < 0 else "#2ecc71" for v in ic_data.values]
    ax.bar(ic_data.index, ic_data.values, color=colors, alpha=0.8)
    ax.axhline(y=0, color="gray", linestyle="--", linewidth=0.5)
    ax.set_title("Factor RankIC", fontsize=12)
    ax.set_ylabel("RankIC")
    fig.tight_layout()
    return _fig_to_base64(fig)

def plot_ic_trend(ic_history: pd.DataFrame) -> str:
    if ic_history.empty:
        return ""
    fig, ax = plt.subplots(figsize=(12, 5))
    for col in ic_history.columns:
        ax.plot(ic_history.index, ic_history[col], label=col, alpha=0.7)
    ax.axhline(y=0, color="gray", linestyle="--", linewidth=0.5)
    ax.legend(loc="best", fontsize=8)
    ax.set_title("Factor IC Trend (20d)", fontsize=12)
    fig.tight_layout()
    return _fig_to_base64(fig)

def plot_pnl_curve(pnl_series: pd.Series) -> str:
    if pnl_series.empty:
        return ""
    fig, ax = plt.subplots(figsize=(12, 5))
    ax.fill_between(pnl_series.index, pnl_series.values, alpha=0.3, color="#3498db")
    ax.plot(pnl_series.index, pnl_series.values, color="#2980b9", linewidth=1.5)
    ax.set_title("Strategy NAV Curve", fontsize=12)
    ax.set_ylabel("NAV")
    ax.yaxis.set_major_formatter(mticker.FormatStrFormatter("%.4f"))
    fig.tight_layout()
    return _fig_to_base64(fig)

REPORT_CSS = """<style>
body{font-family:-apple-system,"Microsoft YaHei",sans-serif;max-width:960px;margin:0 auto;padding:20px;color:#333}
h1{color:#2c3e50;border-bottom:2px solid #3498db;padding-bottom:8px}
h2{color:#34495e;margin-top:28px}
table{border-collapse:collapse;width:100%;margin:12px 0}
th,td{border:1px solid #ddd;padding:8px 12px;text-align:left}
th{background:#3498db;color:#fff;font-weight:600}
tr:nth-child(even){background:#f8f9fa}
img{max-width:100%;height:auto;margin:12px 0;border-radius:4px;box-shadow:0 1px 4px rgba(0,0,0,0.1)}
.meta{color:#999;font-size:12px;margin-bottom:20px}
.good{color:#27ae60;font-weight:600}
.bad{color:#e74c3c;font-weight:600}
.warn{color:#f39c12;font-weight:600}
.footer{margin-top:40px;padding-top:12px;border-top:1px solid #eee;color:#aaa;font-size:11px}
</style>"""

def render_html(title, sections, report_date=""):
    parts = [f"<h1>{title}</h1>"]
    if report_date:
        parts.append(f'<p class="meta">{report_date}</p>')
    for sec in sections:
        parts.append(f"<h2>{sec.get('heading','')}</h2>")
        if sec.get("content"):
            parts.append(f"<div>{sec['content']}</div>")
        for img in sec.get("images", []):
            if img:
                parts.append(f'<img src="data:image/png;base64,{img}" />')
    parts.append(f'<div class="footer">Generated by investment-engine | {datetime.now().strftime("%Y-%m-%d %H:%M")}</div>')
    html = f"""<!DOCTYPE html><html><head><meta charset="utf-8"><title>{title}</title>{REPORT_CSS}</head><body>{"".join(parts)}</body></html>"""
    return html

def save_report(html, report_type, subdir="daily"):
    today = datetime.now()
    month_dir = Path(IE_ROOT) / "reports" / subdir / today.strftime("%Y-%m")
    month_dir.mkdir(parents=True, exist_ok=True)
    fpath = month_dir / f"{today.strftime('%Y-%m-%d')}-{report_type}.html"
    fpath.write_text(html, encoding="utf-8")
    _cleanup(month_dir, 30 if subdir == "daily" else 365)
    return str(fpath)

def _cleanup(directory, keep_days):
    cutoff = datetime.now() - timedelta(days=keep_days)
    for f in directory.glob("*.html"):
        try:
            t = datetime.fromtimestamp(f.stat().st_mtime)
            if t < cutoff:
                f.unlink()
        except: pass

def make_table(headers, rows):
    ths = "".join(f"<th>{h}</th>" for h in headers)
    trs = "".join(f"<tr>{''.join(f'<td>{c}</td>' for c in row)}</tr>" for row in rows)
    return f"<table><thead><tr>{ths}</tr></thead><tbody>{trs}</tbody></table>"

def make_metric_row(metrics):
    cards = ""
    for label, value, cls in metrics:
        cards += f'<div style="display:inline-block;min-width:120px;padding:8px 16px;margin:4px;background:#f8f9fa;border-radius:6px;text-align:center"><div style="font-size:11px;color:#888">{label}</div><div class="{cls}" style="font-size:18px">{value}</div></div>'
    return f'<div style="margin:12px 0">{cards}</div>'
